# Generated by Django 5.0.3 on 2024-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_capa',
            field=models.ImageField(upload_to='IMG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto_texto',
            field=models.ImageField(upload_to='IMG'),
        ),
    ]
