# Generated by Django 5.0.3 on 2024-04-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_foto_capa_alter_post_foto_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_publicação',
            new_name='data_publicacao',
        ),
    ]
