# Generated by Django 5.0.3 on 2024-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(choices=[('a', 'Ajuda'), ('e', 'Elogio'), ('s', 'Sugestão')], max_length=1),
        ),
    ]
