# Generated by Django 5.0.4 on 2024-04-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='IMG')),
                ('texto1', models.CharField(max_length=100)),
                ('texto2', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(choices=[('CH', 'Ciências Humanas'), ('CE', 'Ciências Exatas'), ('BIO', 'Biociências')], default='BIO', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='IMG'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero_parcelas',
            field=models.IntegerField(),
        ),
    ]
